#### Dataframe to Series using Squeeze

In [2]:
import pandas as pd
# df = pd.read_csv("C:/Users/shiva/Downloads/archive/youtube_2025_dataset_202504061614.csv")
df=pd.read_csv("youtube_2025_dataset_202504061614.csv").squeeze('columns')
# print(df)
df
# type(df)

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [3]:
# Squeeze - For converting Dtaframe to Series 
df1=pd.read_csv("yt_data_one_column.csv").squeeze('columns')
df1

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

In [4]:
type(df1)

pandas.Series

In [35]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
df=pd.read_excel("yt_data_two_columns.csv.xlsx", index_col="Youtuber Name")
df

                    Total Videos
Youtuber Name
Eric Patel                    68
Cynthia Harrington           128
Amanda Walker                282
Jessica Nelson MD            302
Matthew Sherman              129
...                          ...
Jasmine Smith                106
John Rasmussen               130
Lisa Burke                   179
Steve Diaz                   182
Austin Tate                   92

[5000 rows x 1 columns]

In [6]:
type(df)

pandas.DataFrame

In [7]:
df=pd.read_excel("yt_data_two_columns.csv.xlsx", index_col="Youtuber Name").squeeze('columns')
df

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

## Pandas Series Attributes

- **values** → Returns the data values.
- **index** → Returns the index labels.
- **dtype** → Returns the data type of values.
- **size** → Returns the total number of elements.
- **shape** → Returns the shape of the Series.
- **ndim** → Returns the number of dimensions.
- **name** → Returns the name of the Series.
- **is_unique** → Checks whether all values are unique.

In [12]:
print(df.values)
print(df.index)
print(df.dtype)
print(df.size)
print(df.shape)
print(df.ndim)
print(df.name)
print(df.is_unique)

[ 68 128 282 ... 179 182  92]
Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)
int64
5000
(5000,)
1
Total Videos
False

In [16]:
print(pd.Series([1,2,3,4,5,5]).is_unique)
print(pd.Series([1,2,3,4,5,]).is_unique)

False
True

## Pandas Series Methods

### 1. head()
- Returns the first 5 rows/elements by default.
- Used to preview the top portion of the dataset.
- You can specify the number of rows to display.
  - `head(10)` → First 10 rows
  - `head(7)` → First 7 rows

### 2. tail()
- Returns the last 5 rows/elements by default.
- Used to preview the bottom portion of the dataset.
- You can specify the number of rows to display.
  - `tail(10)` → Last 10 rows
  - `tail(7)` → Last 7 rows

### 3. sample()
- Returns a random row or rows from the dataset.
- Useful for checking random records.
- Example:
  - `sample()` → 1 random row
  - `sample(5)` → 5 random rows

### value_counts()

- Returns the count of each unique value in a Series.
- Useful for frequency analysis.
- Results are sorted in descending order by default.

Example:
`series.value_counts()`

### sort_values()

- Sorts the values in a Series.
- By default, sorting is done in ascending order.
- Use `ascending=False` for descending order.

Example:
`series.sort_values()`
`series.sort_values(ascending=False)`

### sort_index()

- Sorts a Series based on its index labels.
- By default, sorting is in ascending order.
- Use `ascending=False` for descending order.

Example:
`series.sort_index()`
`series.sort_index(ascending=False)`

In [24]:
print(df.head())
print(df.tail())
print(df.sample(3))
df=pd.Series(['a','b','c','a','d','e','e','f','a'])
print(df.value_counts())  # Returns the frequency of each element
print(df.sort_values())
print(df.sort_values(ascending=False))

s = pd.Series(
    [100, 200, 300],
    index=['c', 'a', 'b']
)

print("Original Series:")
print(s)

print("\nSorted by Index:")
print(s.sort_index())

0    a
1    b
2    c
3    a
4    d
dtype: str
4    d
5    e
6    e
7    f
8    a
dtype: str
2    c
6    e
3    a
dtype: str
a    3
e    2
b    1
c    1
d    1
f    1
Name: count, dtype: int64
0    a
3    a
8    a
1    b
2    c
4    d
5    e
6    e
7    f
dtype: str
7    f
5    e
6    e
4    d
2    c
1    b
0    a
3    a
8    a
dtype: str
Original Series:
c    100
a    200
b    300
dtype: int64

Sorted by Index:
a    200
b    300
c    100
dtype: int64

### Method Chaining

- Method chaining allows multiple methods to be called in a single statement.
- The result of one method is passed to the next method.
- Makes code concise and readable.

Syntax:
`object.method1().method2().method3()`

In [25]:
s = pd.Series([5, 2, 8, 1, 3, 2])

result = (
    s.value_counts()
     .sort_values(ascending=False)
     .head(3)
)

print(result)

2    2
5    1
8    1
Name: count, dtype: int64